Sklearn Содержит:
### Множество моделей:
 - Включая линейную регрессию  
 - (from sklearn.linear_model import LinearRegression)
### Методы оценки качества
- Включая mse
- (from sklearnmetrics import mean_squared_error)
### Методы разделения данных
- Включая разделение на выборку для обучения и выборку для валидации
- (from sklearn.model_selection import train_test_split)

### Единый подход для всех моделей
from sklearn.linear_model import LinearRegression
x,y = КАКИЕ-ТО ДАННЫЕ
model = LinearRegression(fit_intercept=True)
model.fit(X, y)
prediction = model.predict(x)

In [73]:
import pandas as pd
import numpy as np
from skimage.metrics import mean_squared_error

In [74]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [75]:
df = pd.DataFrame(data, columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'])
df['MEDV'] = target

In [76]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [80]:
# Отделить колонки с признаками от колонки с целевой переменной (которую прогнозируем)
# это нужно для корректной работы sklearn
X = df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']]
y = df['MEDV']

In [81]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [82]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [83]:
# Разделить данные на часть для обучения и часть для проверки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [84]:
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
345,0.03113,0.0,4.39,0.0,0.442,6.014,48.5,8.0136,3.0,352.0,18.8,385.64,10.53
357,3.84970,0.0,18.10,1.0,0.770,6.395,91.0,2.5052,24.0,666.0,20.2,391.34,13.27
464,7.83932,0.0,18.10,0.0,0.655,6.209,65.4,2.9634,24.0,666.0,20.2,396.90,13.22
308,0.49298,0.0,9.90,0.0,0.544,6.635,82.5,3.3175,4.0,304.0,18.4,396.90,4.54
223,0.61470,0.0,6.20,0.0,0.507,6.618,80.8,3.2721,8.0,307.0,17.4,396.90,7.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,13.35980,0.0,18.10,0.0,0.693,5.887,94.7,1.7821,24.0,666.0,20.2,396.90,16.35
37,0.08014,0.0,5.96,0.0,0.499,5.850,41.5,3.9342,5.0,279.0,19.2,396.90,8.77
382,9.18702,0.0,18.10,0.0,0.700,5.536,100.0,1.5804,24.0,666.0,20.2,396.90,23.60
366,3.69695,0.0,18.10,0.0,0.718,4.963,91.4,1.7523,24.0,666.0,20.2,316.03,14.00
162,1.83377,0.0,19.58,1.0,0.605,7.802,98.2,2.0407,5.0,403.0,14.7,389.61,1.92

In [85]:
X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
46,0.18836,0.0,6.91,0.0,0.448,5.786,33.3,5.1004,3.0,233.0,17.9,396.90,14.15
335,0.03961,0.0,5.19,0.0,0.515,6.037,34.5,5.9853,5.0,224.0,20.2,396.90,8.01
264,0.55007,20.0,3.97,0.0,0.647,7.206,91.6,1.9301,5.0,264.0,13.0,387.89,8.10
353,0.01709,90.0,2.02,0.0,0.410,6.728,36.1,12.1265,5.0,187.0,17.0,384.46,4.50
396,5.87205,0.0,18.10,0.0,0.693,6.405,96.0,1.6768,24.0,666.0,20.2,396.90,19.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,0.13960,0.0,8.56,0.0,0.520,6.167,90.0,2.4210,5.0,384.0,20.9,392.69,12.33
123,0.15038,0.0,25.65,0.0,0.581,5.856,97.0,1.9444,2.0,188.0,19.1,370.31,25.41
113,0.22212,0.0,10.01,0.0,0.547,6.092,95.4,2.5480,6.0,432.0,17.8,396.90,17.09
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03
130,0.34006,0.0,21.89,0.0,0.624,6.458,98.9,2.1185,4.0,437.0,21.2,395.04,12.60

In [86]:
y_train

345    17.5
357    21.7
464    21.4
308    22.8
223    30.1
       ...
394    12.7
37     21.0
382    11.3
366    21.9
162    50.0
Name: MEDV, Length: 404, dtype: float64

In [87]:
y_test

46     20.0
335    21.1
264    36.5
353    30.1
396    12.5
       ...
104    20.1
123    17.3
113    18.7
478    14.6
130    19.2
Name: MEDV, Length: 102, dtype: float64

### Делаем модель

In [88]:
from sklearn.linear_model import LinearRegression

In [89]:
lr = LinearRegression()

In [90]:
lr.fit(X_train, y_train)

LinearRegression()

In [91]:
lr.coef_

array([-4.80149673e-02,  4.73741182e-02,  2.57028815e-02,  2.87727566e+00,
       -1.91673055e+01,  3.73417373e+00,  4.52662614e-03, -1.56410577e+00,
        3.24779111e-01, -1.32619217e-02, -9.23427642e-01,  9.58884098e-03,
       -5.84715040e-01])

# Оценить качество модели на отложенных данных

In [92]:
lr.predict(X_test)

array([20.19419883, 20.66673728, 35.9739316 , 25.22337262, 19.36492073,
       25.56385771, 10.21870509, 30.65371569, 36.7396436 ,  8.60956857,
       11.45452315, 17.81664622, 25.13850934, 13.10846955, 19.56814406,
       25.91097617, 19.46066009, 18.55978563, 24.8118337 , 17.48831215,
       32.1549851 , 22.47147826, 20.22334385, 26.73803574, 20.70162326,
       23.95720751, 36.20540876, 36.06174769, 17.3572687 , 20.24130901,
       13.52699086, 29.25658581, 22.2618707 , 14.12971749, 14.11982357,
       20.63245484, 24.05463292, 21.80329066, 22.41643561, 19.55026027,
       33.49299239, 21.34445842, 18.67619888, 17.74892086, 27.44304561,
       26.71689098, 24.92046769, 19.16267255, 11.87568512, 31.10207305,
       17.05654874, 19.318669  , 31.61609987, 19.4446184 , 15.70949168,
       25.28427252, 31.64932503, 25.31744298, 16.18996536, 24.59081504,
       31.74046269, 28.09693503, 20.26855496, 10.87214379, 23.41611474,
       24.07630628, 13.64556559, 19.62872696, 22.93160089, 25.26347489,
       25.16726917, 23.00274286, 18.19847426,  6.93155388, 41.03927553,
       30.68779507, 33.90639846, 13.52834495, 10.32398491, 16.8039042 ,
       13.10061003, 30.04421177, 34.28864322, 15.34052686, 17.71822509,
       19.87345826, 25.28203522, 14.58183224, 24.01578221, 22.96732234,
       23.91783738, 20.62441085, 23.06595626, 21.15911   , 17.75615721,
       23.77453361, 18.43634142, 21.62968617, 15.93953442, 20.49917322,
       19.69778848, 20.12932572])

In [93]:
#оценка на глаз
pd.DataFrame((y_test.values, lr.predict(X_test))).T

        0          1
0    20.0  20.194199
1    21.1  20.666737
2    36.5  35.973932
3    30.1  25.223373
4    12.5  19.364921
..    ...        ...
97   20.1  21.629686
98   17.3  15.939534
99   18.7  20.499173
100  14.6  19.697788
101  19.2  20.129326

[102 rows x 2 columns]

In [94]:
from sklearn.metrics import mean_squared_error
## Оцениваем при помощи MSE среднее квадратичное отклонение
mean_squared_error(y_test, lr.predict(X_test))

13.110155430916814

In [95]:
#Оценка переобучения
mean_squared_error(y_train, lr.predict(X_train))

24.49522637494586