#Чтение данны
"""
pd.read_csv("Полный_путь_к_файлу/название_файла.csv")

Некоторые параметры функции read_csv:

sep — разделитель данных, по умолчанию ',' ;

decimal — разделитель числа на целую и дробную часть, по умолчанию '.' ;

names — список с названиями колонок, необязательный параметр;

skiprows — если файл содержит системную информацию, можно её пропустить, необязательный параметр.
"""

In [11]:
import pandas as pd
football = pd.read_csv("football.csv") #если лежит в той же папке что и блокнот
display(football.head(10)) #.tail())

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
5,5,E. Hazard,27,Belgium,Chelsea,93000000,340000,LF,81,84,...,86,91,34,27,22,11,12,6,8,8
6,6,L. Modrić,32,Croatia,Real Madrid,67000000,420000,RCM,86,72,...,82,84,60,76,73,13,9,7,14,9
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
8,8,Sergio Ramos,32,Spain,Real Madrid,51000000,380000,RCB,66,60,...,75,82,87,92,91,11,8,9,7,11
9,9,J. Oblak,25,Slovenia,Atlético Madrid,68000000,94000,GK,13,11,...,11,70,27,12,18,86,92,78,88,89

In [17]:
#Получение информации о наборе данных INFO
display(football.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12897 non-null  int64
 1   Name             12897 non-null  object
 2   Age              12897 non-null  int64
 3   Nationality      12897 non-null  object
 4   Club             12897 non-null  object
 5   Value            12897 non-null  int64
 6   Wage             12897 non-null  int64
 7   Position         12897 non-null  object
 8   Crossing         12897 non-null  int64
 9   Finishing        12897 non-null  int64
 10  HeadingAccuracy  12897 non-null  int64
 11  ShortPassing     12897 non-null  int64
 12  Volleys          12897 non-null  int64
 13  Dribbling        12897 non-null  int64
 14  Curve            12897 non-null  int64
 15  FKAccuracy       12897 non-null  int64
 16  LongPassing      12897 non-null  int64
 17  BallControl      12897 non-null  int64
 18  Acceleration     12897 non-null  int64
 19  SprintSpeed      12897 non-null  int64
 20  Agility          12897 non-null  int64
 21  Reactions        12897 non-null  int64
 22  Balance          12897 non-null  int64
 23  ShotPower        12897 non-null  int64
 24  Jumping          12897 non-null  int64
 25  Stamina          12897 non-null  int64
 26  Strength         12897 non-null  int64
 27  LongShots        12897 non-null  int64
 28  Aggression       12897 non-null  int64
 29  Interceptions    12897 non-null  int64
 30  Positioning      12897 non-null  int64
 31  Vision           12897 non-null  int64
 32  Penalties        12897 non-null  int64
 33  Composure        12897 non-null  int64
 34  Marking          12897 non-null  int64
 35  StandingTackle   12897 non-null  int64
 36  SlidingTackle    12897 non-null  int64
 37  GKDiving         12897 non-null  int64
 38  GKHandling       12897 non-null  int64
 39  GKKicking        12897 non-null  int64
 40  GKPositioning    12897 non-null  int64
 41  GKReflexes       12897 non-null  int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

None

In [17]:
#Получение информации о наборе данных INFO
display(football.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12897 non-null  int64
 1   Name             12897 non-null  object
 2   Age              12897 non-null  int64
 3   Nationality      12897 non-null  object
 4   Club             12897 non-null  object
 5   Value            12897 non-null  int64
 6   Wage             12897 non-null  int64
 7   Position         12897 non-null  object
 8   Crossing         12897 non-null  int64
 9   Finishing        12897 non-null  int64
 10  HeadingAccuracy  12897 non-null  int64
 11  ShortPassing     12897 non-null  int64
 12  Volleys          12897 non-null  int64
 13  Dribbling        12897 non-null  int64
 14  Curve            12897 non-null  int64
 15  FKAccuracy       12897 non-null  int64
 16  LongPassing      12897 non-null  int64
 17  BallControl      12897 non-null  int64
 18  Acceleration     12897 non-null  int64
 19  SprintSpeed      12897 non-null  int64
 20  Agility          12897 non-null  int64
 21  Reactions        12897 non-null  int64
 22  Balance          12897 non-null  int64
 23  ShotPower        12897 non-null  int64
 24  Jumping          12897 non-null  int64
 25  Stamina          12897 non-null  int64
 26  Strength         12897 non-null  int64
 27  LongShots        12897 non-null  int64
 28  Aggression       12897 non-null  int64
 29  Interceptions    12897 non-null  int64
 30  Positioning      12897 non-null  int64
 31  Vision           12897 non-null  int64
 32  Penalties        12897 non-null  int64
 33  Composure        12897 non-null  int64
 34  Marking          12897 non-null  int64
 35  StandingTackle   12897 non-null  int64
 36  SlidingTackle    12897 non-null  int64
 37  GKDiving         12897 non-null  int64
 38  GKHandling       12897 non-null  int64
 39  GKKicking        12897 non-null  int64
 40  GKPositioning    12897 non-null  int64
 41  GKReflexes       12897 non-null  int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

None

In [23]:
display(football.describe()) #число непропущенных значений, среднее, отклонение, диапазон(макс, мин) ,  медиану и прочие стат. характеристики

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,...,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,...,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,...,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,...,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,...,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,...,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,...,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,...,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [29]:
#для учета нечисловых значений необходимо указать тип
football.describe(include = ['object'])

                Name Nationality              Club Position
count          12897       12897             12897    12897
unique         12326         156               650       27
top     J. Rodríguez     England  V-Varen Nagasaki       GK
freq               9        1368                30     1641

In [33]:
#отображение данных без обрезки
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(football.describe())

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,44.264403,40.321625,50.115143,55.463596,63.109715,63.205629,61.819648,59.430565,63.171978,52.530666,64.285415,61.123052,64.271614,43.971931,53.777933,44.875940,47.166008,50.843374,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,17.781283,16.718481,15.215160,16.692643,15.129988,14.903845,14.858729,8.875832,14.190700,16.975214,11.765467,16.194498,12.550696,18.769749,17.232716,20.188799,19.245882,13.745960,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,6.000000,3.000000,9.000000,5.000000,12.000000,12.000000,15.000000,21.000000,16.000000,2.000000,15.000000,12.000000,17.000000,3.000000,11.000000,3.000000,2.000000,10.000000,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,32.000000,29.000000,40.000000,51.000000,55.000000,55.000000,53.000000,54.000000,55.000000,42.000000,57.000000,54.000000,57.000000,29.000000,41.000000,24.000000,35.000000,42.000000,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,45.000000,39.000000,53.000000,60.000000,66.000000,66.000000,64.000000,59.000000,65.000000,56.000000,65.000000,64.000000,65.000000,47.000000,56.000000,51.000000,52.000000,52.000000,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,58.000000,52.000000,61.000000,65.000000,74.000000,73.000000,72.000000,65.000000,73.000000,65.000000,72.000000,72.000000,73.000000,59.000000,67.000000,62.000000,61.000000,60.000000,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,93.000000,94.000000,93.000000,96.000000,97.000000,96.000000,96.000000,96.000000,96.000000,95.000000,95.000000,96.000000,97.000000,94.000000,95.000000,92.000000,95.000000,94.000000,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000